# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  CodeStyle:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install flake8
      - name: Codestyle
        run: python -m flake8 ./ --ignore=F401,E402

  Tests:
    needs: CodeStyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: tests
        run: |
          pip3 install -e '.[test]'
          python3 -m coverage run -m pytest
          python3 -m coverage html -d coverage_html
          
      - name: upload artifact
      - name: send artifact to telegram

#${{ secrets.TELEGRAM_TO_DEBUG }}
#${{ secrets.TELEGRAM_TOKEN_DEBUG }}


  TelegramNotification:
    runs-on: ubuntu-latest
    needs: Tests
    if: failure()
    steps:
      - name: send error message
